player-count: 0
chat-format: "%playerRank% %playerRole% &7%playerName%: &r%message%"
message-format: "&7[%sender%->%recipient%]: &f%message%"
spawn: "world,0,100,0,0,0"
teleport-delay: 5
land-claim-tool: "GOLD_HOE"
land-claim-tool-lore: "&eLand Claim Tool"
claim-block-price: "10"
messages:
    welcome: "&aWelcome back, %playerName%!"
    quit: "&c%playerName% has left."
    first-time-welcome: "&a&lWelcome, &r%playerName%&a&l, to ImagineCraft! &rYou are player #%playerNumber%."
    player-only-command: "&cOnly players can run that command!"
    unknown-command: "&cUnknown commmand (%label%)! &fTry /help"
    unknown-player: "&cUnknown player (%playerName%)!"
    unknown-role: "&cUnknown role (%role%)!"
    updated-role: "&aUpdated role for %playerName%."
    forbidden-command: "&cYou are not allowed to use that command!"
    reloaded-config: "&aReloaded config."
    reset-config: "&aReset config."
    command-usage: "&cUsage: &r%usage%"
    set-spawn: "&aSet the spawn to your current location."
    teleport: "&aTeleporting to %destination%..."
    teleportation-completed: "&aTeleportation complete."
    teleportation-cancelled: "&cTeleportation cancelled."
    teleport-request: "&aRequested teleport to %target%."
    teleport-request-target: "&a%requester% requested to teleport to you. &rType /tpaccept or /tpdeny."
    teleport-request-accepted: "&aTeleport request accepted."
    teleport-request-denied: "&cTeleport request denied."
    no-pending-request: "&cYou don't have a pending teleportation request!"
    help-header: "&a---------- &7Help (%currentPage%/%totalPages%) &a----------"
    teleport-to-self: "&cYou can't teleport to yourself!"
    no-conversation: "&cThere is no one to reply to!"
    inventory-cleared: "&aCleared your inventory."
    land-not-owned: "&cYou don't own the land you are standing on!"
    unclaimed-land: "&aYou unclaimed the land you are standing on."
    display-coins: "&aYou have &f%coins% &acoins."
    no-claim-selection: "&cFirst make a selection with the tool given in &r/claimtool&c!"
    different-worlds: "&cYour selection points are in two different worlds!"
    claim: "&aClaimed your selected area."
    receive-claim-tool: "&aYou have received a land claim tool."
    restart: "&cServer restarting. We will be back in a few seconds!"